config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # delete "bookmarks/:id", to: "bookmarks#destroy", as: "delete_book"
  root to: "lists#index"
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: {minimum: 6}
  validates :movie_id, uniqueness: {scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  validates :name, uniqueness: true, presence: true
  has_one_attached :poster
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :rating, numericality: {in: [0, 1, 2, 3, 4, 5]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = List.find(params[:list_id])
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @review = Review.new
    @list = List.find(params[:id])
    @reviews = @list.reviews
    @moy = (@reviews.map { |review| review.rating }.sum.to_f / @reviews.count).round(1)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(lists_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def lists_params
    params.require(:list).permit(:name, :poster)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    
    @review = Review.new(reviews_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      redirect_to list_path(@list)
    end
  end

  private

  def reviews_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="container margin-under-navbar p-5">

  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie, input_html: { class: 'select2' } %>

    <%= f.button :submit, "Soumettre", class: "btn-outline-primary" %>
    <%= link_to "Cancel", list_path(@list), class: "btn-outline-secondary" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c59b277e6e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top bg-white">
      <div class="container-fluid">

        <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarSupportedContent">
          <h1><i class="fa-regular fa-file-video"></i></h1>
          <ul class="navbar-nav">
              <li class="nav-item active">
                <%= link_to "Mes listes", root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Nouvelle liste", new_list_path, class: "nav-link" %>
              </li>
              <!--li class="nav-item"-->
              <!--/li-->
          </ul>
        </div>
      </div>
    </div>

    
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner margin-under-navbar" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
   url(https://s3-us-west-2.amazonaws.com/prd-rteditorial/wp-content/uploads/2018/03/13153742/RT_300EssentialMovies_700X250.jpg);">
  <div class="container">
    <h1>My lists of <strong>movies</strong> !</h1>
    <p>See all my lists of movies.</p>
    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<div class="container">
  <div class="ctr d-flex flex-wrap">
      <% @lists.each do |list| %>
        <% if list.poster.attached? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
              url('<%= cl_image_path list.poster.key, height: 300, crop: :fill %>')">
        <% else %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
              url(https://www.benefsnet.com/images/cms/film.gif)">
        <% end %>
            <%= link_to list.name.capitalize,  list_path(list)%>
          </div>
      <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container pd-5 margin-under-navbar">

  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :poster, as: :file %>
    <%= f.button :submit, "Soumettre", class: "btn-outline-primary" %>
    <%= link_to "Cancel", root_path, class: "btn-outline-secondary" %>
  <% end %>

</div>

app/views/lists/show.html.erb
<% if @list.poster.attached? %>
  <div class="banner margin-under-navbar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url('<%= cl_image_path @list.poster.key%>')">
<% else %>
  <div class="banner margin-under-navbar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
      url(https://www.benefsnet.com/images/cms/film.gif)">
<% end %>
  <div class="container">
    <h1><%= @list.name.capitalize %></h1>  

    <%# <a class="btn btn-flat" href="#">Apply now</a> %>
  </div>
</div>

<%= link_to "Nouveau bookmark",  new_list_bookmark_path(@list), class: "btn btn-gradient"%>


  <div class="container">
  <h3><%= @moy %> / 5</h3>
  <br>
<table class="table table-hover border-bottom pb-4">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Movie</th>
      <th scope="col">Comment</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>

    <% @list.bookmarks.each_with_index do |bookmark, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= bookmark.movie.title %></td>
        <td><%= bookmark.comment %></td>
        <td><%= link_to "", bookmark_path(bookmark), method: "delete", class: "fa-solid fa-trash-can" %></td>
      </tr>
    <% end %>
  
  </tbody>
</table>

<div class="d-flex justify-content-between mb-5">
  <div class="d-flex flex-column mt-5 w-50">
  <ul class="list-group m-4">
    <% @list.reviews.each_with_index do |review, index| %>
      <li class="list-group-item">
        <td><% review.rating.times do %>
              <i class="fa-solid fa-star"></i>
            <% end %>
            <% (5-review.rating).times do %>
              <i class="fa-regular fa-star"></i>
            <% end %>
        </td>
        <td>      </td>
        <td class="pl-2"><%= review.comment %></td>
      </li>
    <% end %>
  </ul>
  </div>

  <div class="container mt-5 w-50">
    <%= simple_form_for [@list, @review] do |f| %>
      <%= f.input :comment %>
      <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5]%>

      <%= f.button :submit, "Commenter", class: "btn-outline-primary" %>
      <%= link_to "Cancel", list_reviews_path(@list), class: "btn-outline-secondary" %>
    <% end %>
  </div>

</div>
  </div>